main: co.pvphub.multilib.ExamplePlugin
name: MultiLibKtExample
authors:
  - MattMX
version: 1.0
api-version: 1.15
commands:
  multi-lib-example-var:
    permission: "multilib.sync.example"
    description: Test the example global variable